### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by HettieM** [Lizzy-j/JS-carousel#3]
Image elements do not have [alt] attributes:

img.projectpicother
img.projectpic
img.projectpic
img#lastClone.carousel_photo
img.carousel_photo
img.carousel_photo
img.carousel_photo
img.carousel_photo
img.carousel_photo
img#firstClone.carousel_photo

**Comment by Lizzy-j** [comment]
Added descriptive text to carousel images (alt tags)
